### ISSUE TITLE
Annoying suggestions appear on comma

### ISSUE THREAD

**Issue by tasop-rsconnect** [prosser/json-schema-validation-extension#3]
Example: 
![image](https://user-images.githubusercontent.com/44773866/161521762-da29fd9c-7642-47fd-a283-d4a36b9367ee.png)

This happens every time a comma is typed after a property. I generally want to start a new line after a comma, but pressing enter accepts the suggestion, making `Item 0` appear.

**Comment by prosser** [comment]
That's a VS Code issue, sorry. This extension doesn't provide any suggestion hooks.
